### ISSUE TITLE
Can you publish to ruby gems?

### ISSUE THREAD

**Issue by eruma** [hfwang/omniauth-paypal-permissions#1]
I added `gem "omniauth-paypal-permissions"` to `Gemfile` and `bundle install`,  given

```
Could not find gem 'omniauth-paypal-permissions (>= 0) ruby' in any of the gem sources listed in your Gemfile..
```

We want to use this nice strategy, can you publish to `rubygems.org`?

**Comment by hfwang** [comment]
Oh wow. No worries.

I published it. BTW in the future, you can use something like the following if you want to just have bundler pull the gem from git:

``` ruby
gem "omniauth-paypal-permissions", git: "git@github.com:hfwang/omniauth-paypal-permissions.git"
```

**Comment by eruma** [comment]
Thanks! :smile:
